apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcfly
  namespace: mcfly
spec:
  chart:
    spec:
      chart: web-app
      version: "=1.0.5"
      sourceRef:
        kind: HelmRepository
        name: artifactory
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: mcfly
  valuesFrom:
  - kind: ConfigMap
    name: mcfly-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity